### ISSUE TITLE
 TypeError: 'null' is not an object

### ISSUE THREAD

**Issue by shoppon** [gruntjs/grunt-contrib-jasmine#102]
the Gruntfile.js
```javascript
module.exports = function(grunt) {
	grunt.initConfig({
		jshint: {
			files: ['js/lib/xp.js'],
		},

		jasmine: {
			pivotal: {
				src: 'js/lib/xp.js',
				options: {
					specs: 'js/lib/xpSpec.js'
				}
			}
		}
	});

	grunt.loadNpmTasks('grunt-contrib-jshint');
	grunt.loadNpmTasks('grunt-contrib-jasmine');

	grunt.registerTask('default', ['jshint', 'jasmine']);
}
```

the package.json
```json
{
	"name": "summary",
	"version": "0.0.1",
	"devDependencies": {
		"grunt": "~0.4.2",
		"grunt-contrib-jshint": "~0.6.0",
		"grunt-contrib-jasmine": "~0.5.1",
		"grunt-template-jasmine-requirejs": "~0.1.8"
	}
}
```

then I got the error:

create:: encountered a declaration exception: failed
  TypeError: 'null' is not an object (evaluating 'jasmine.getEnv().currentSpec.e
xpect') in file:///D:/workspace/summary/.grunt/grunt-contrib-jasmine/jasmine.js
(line 526) (1)

Can anyone help me resolve this?

**Comment by rtaborda** [comment]
+Any updates on this issue? I'm also using angularJS + jasmine + grunt and get exactly the same error :disappointed:

**Comment by rtaborda** [comment]
This issue for me was caused because of bad configuration. Feel free to close it.

**Comment by MAXakaWIZARD** [comment]
@rtaborda Could you please tell what was wrong with your configuration? Cause I'm experiencing same issue.

**Comment by rtaborda** [comment]
I don't remember exactly but from what I could see I was actually passing the specs in the "src", instead of passing the original files. And don't forget the app.js, which in my case is the one that contains the angularjs configurations and routing.

This is what I have since I fixed it:
```javascript
jasmine: {
	pivotal: {
		src: [
			'public/controllers/**/*.js',
			'public/models/**/*.js',
			'public/js/app.js'
		],
		options: {
			specs: 'tests/unit_tests/specs/*.spec.js',
			vendor: [
				'public/js/libs/angular.min.js',
				'public/js/libs/angular-route.min.js',
				'public/js/libs/angular-mocks.js'
			]
		}
	}
}
```

**Comment by MAXakaWIZARD** [comment]
@rtaborda Thanks

**Comment by rtaborda** [comment]
You're welcome, hope it helped :)
