### ISSUE TITLE
ReferenceError: Can't find variable: module

### ISSUE THREAD

**Issue by parikshitN** [gruntjs/grunt-contrib-jasmine#105]
Trying to run  a jasmine test for project built using yeoman. I installed the jasmine plugin for grunt using 
npm install grunt-contrib-jasmine --save-dev

While trying to run the jasmin task, I get the below error

ReferenceError: Can't find variable: module in file:///E:/Personal%20Projects/
yeoman-projects/test-app/test/spec/controllers/main.js (line 6) (1)

How to resolve this ? 

Thanks,
Pariskhit

**Comment by nmccready** [comment]
@austinkeeley I am having the same issue but the files are there. The problem I have is angular-mocks.js expects `window.jasmine` to be loaded before itself is loaded. However since angular-mock.js is a vendor lib it always comes b4 jamsmine. I don't know how this was working prior.

**Comment by FlavorScape** [comment]
same issue. jasmine works in phantom browser with Karma, but not in grunt or browser....

**Comment by resah** [comment]
Hi there,
if you happen to stumble across this issue ... I had the same error until I noticed, that all `src` files will be loaded in alphabetical order. So `module` is probably not initialized yet.

Either rename the file where you declare your module variable to something starting with `a` (ouch) or explicitly define file order in `src` array.

Regards
