### ISSUE TITLE
Issue with phantom-polyfill.js

### ISSUE THREAD

**Issue by danielchao** [gruntjs/grunt-contrib-jasmine#107]
Running test suite involving ace.js, which uses Function.prototype.bind(). 

Getting TypeError: instanceof called on an object with an invalid prototype property. at grunt/grunt-contrib-jasmine/phantom-polyfill.js:16

Ace.js uses its own polyfill for bind (which works), but this is replaced by the phantom polyfill during test.

**Comment by guy-mograbi-at-gigaspaces** [comment]
whoever gets here - this snippet worked for me after researching a bit. 

I have to do 2 modifications


1) define `var slice = [].slice`
2) define `var Empty = function(){}`

you can add those right after `var target=this`


Thanks!
