### ISSUE TITLE
Console.log not working

### ISSUE THREAD

**Issue by s10mcow** [gruntjs/grunt-contrib-jasmine#143]
When unit testing sometimes we need to see how a piece of data looks thus we need the console.log. This doesn't work in grunt-contrib-jasmine.

**Comment by renet** [comment]
How can I use the page.onConsoleMessage callback with my Gruntfile.js? Is this possible to define a callback method for the page without having to change the grunt-contrib-jasmine code itself or one of its dependencies?

**Comment by russell-miller** [comment]
I also would like to see an example of adding the `console.log` functionality to my project when running grunt-contrib-jasmine. I don't understand where your example code is supposed to go.

**Comment by Arkni** [comment]
From the source code, this task will print the console messages only in case you have `display` option set to `full`. I didn't test it, though.

**Comment by russell-miller** [comment]
@Arkni you're right. Also, it appears that `console.error` shows up when display is short. So that might be my workaround for now...
