### ISSUE TITLE
"PhantomJS timed out, possibly due to an unfinished async spec" on SLES

### ISSUE THREAD

**Issue by mybecks** [gruntjs/grunt-contrib-jasmine#148]
Hello,

I'm using the grunt-contrib-jasmine package for running my tests. On MacOSX all works fine, but when I want to run them on my CI on SLES 64Bit I always get the following error: 

<pre>
[D] ["phantomjs","fail.timeout"]

Warning: PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue.
</pre>

My Gruntfile looks like this:

<pre>
jasmine: {
            proj: {
                options:{
                    junit:{
                        path: 'tests/test-results',
                        consolitdate: true
                    },
                    '--web-security' : false,
                    '--local-to-remote-url-access' : true,
                    '--ignore-ssl-errors' : true,
                },
                src: 'tests/test.js'
            }
        }
</pre>

test.js:

<pre>
(function(global) {
    "use strict";

    describe("Test Suite", function() {
        it("check", function(done) {
                expect(true).toBe(true);
}
    });
}(window));
</pre>

The `--debug` output can be found on [pastebin](http://pastebin.com/EdQJ2N4a).

It seems that the `test.js` file is not getting executed - it breaks before!
If I run the, not deleted on failure, `_SpecRunner.html` - the test is executed.
BR,
mybecks

**Comment by divyanthj** [comment]
mybecks, how do I remove the HTTP_PROXY and HTTPS_PROXY?

**Comment by mybecks** [comment]
with unset. UNSET HTTP(S)_PROXY
