### ISSUE TITLE
junit reported creates malformed XML

### ISSUE THREAD

**Issue by ukilon-okta** [gruntjs/grunt-contrib-jasmine#160]
When the error message contains html or strings that look like html tags.
One solution could be to to wrap the content of `<failure>` elements in a CDATA block.

**Comment by ControlTheBit** [comment]
We had the same problem, when we tried to transform the XMLs using XSLT.

Seems to be fixed in commit https://github.com/gruntjs/grunt-contrib-jasmine/commit/45a96782ad25d9190ae0bfa352c70d00dcddb505 which was first included in version 0.7.0.

--> Issue can be closed
