### ISSUE TITLE
On failing tests report offenders even when in display: 'short'

### ISSUE THREAD

**Issue by cburgmer** [gruntjs/grunt-contrib-jasmine#161]
As follow up to #119:
In the past failing tests were always reported. This changed along the way and now when `display: 'short'` is configured, failing tests are marked as 'X' in the output. As a result the only way to find the offending test is to temporarily disable the setting in Grunfile.js, which is a rather annoying and leads to accidentally committing the wrong config.

**Comment by dwelle** [comment]
+1

**Comment by cburgmer** [comment]
Apparently there's [options.summary](https://github.com/gruntjs/grunt-contrib-jasmine#optionssummary). Which feels a bit counter intuitive to setup.
