### ISSUE TITLE
Check that required files exist before running

### ISSUE THREAD

**Issue by paazmaya** [gruntjs/grunt-contrib-jasmine#164]
In case using local files, for example in the `options.vendor` array, check that those files exist before running PhantomJS.
This could reduce the time for looking at where possible PhantomJS timeout is occurring, or other similar unexpected result which is caused by missing files.

**Comment by dwelle** [comment]
+1

**Comment by paazmaya** [comment]
@vladikoff Any specific reason for closing this issue?

**Comment by steveoh** [comment]
phantom is no longer supported
