### ISSUE TITLE
PhantomJS doesn't die.

### ISSUE THREAD

**Issue by njhazelh** [gruntjs/grunt-contrib-jasmine#167]
Each time I run jasmine, it spawns a new phantomjs process.  After all tests have run, jasmine ends, but the phantomjs process sticks around.  This is especially a problem when using watch, since I end up running many phantomjs instances, which take up a lot of memory.  Initially, I thought it was a problem with watch, but I get the same problem running just `grunt jasmine`.

![image](https://cloud.githubusercontent.com/assets/3210494/4252303/d46c2e36-3a94-11e4-8b4f-59d561224d61.png)
_result of running jasmine a couple of times._

**Comment by gyandeeps** [comment]
To land the above fix, we need to update the dependency in this project. as this project is still using `0.6.0 ` version and `0.7.0` is needed from grunt-lib-phantomjs

**Comment by gyandeeps** [comment]
I tried it with `0.7.0` version of grunt-lib-phantomjs it fails for me. I am not sure whats gng on.

```sh
152 specs in 3.748s.
>> 0 failures

Done, without errors.
15:39:20 : Test run complete 

PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Used --force, continuing.
>> 0 failures
fs.js:77
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, unlink 'C:\Users\gs025879\AppData\Local\Temp\1435264754241.051'
    at Error (native)

Process finished with exit code 1
```
