### ISSUE TITLE
Keeps failure messages in summary forever

### ISSUE THREAD

**Issue by ungesaeuertesbrot** [gruntjs/grunt-contrib-jasmine#171]
When running the task multiple times within a single process (e.g. in a watch) failure messages that were written into the summary once will remain there forever and be printed over and over again with each run (provided that a summary is requested, obviously), even after the correcponding spec ceases to fail.

Here's the one-line patch that fill fix the issue:

```
 tasks/jasmine.js | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/tasks/jasmine.js b/tasks/jasmine.js
index c140a93..fbaa893 100644
--- a/tasks/jasmine.js
+++ b/tasks/jasmine.js
@@ -172,6 +172,8 @@ module.exports = function(grunt) {
       failed   : 0
     };
 
+    summary.length = 0;
+
     function indent(times) {
       return new Array(+times * tabstop).join(' ');
     }
```

**Comment by mdix** [comment]
#145 is fixed, so this one can be closed it think.

**Comment by vladikoff** [comment]
yeap! Thanks!
