### ISSUE TITLE
Hide Jasmine 2.1.1 top level suite display

### ISSUE THREAD

**Issue by gyandeeps** [gruntjs/grunt-contrib-jasmine#182]
With the new release of Jasmine 2.1.1, now they have a top level suite which is called `Jasmine__TopLevel__Suite` and its id is `suite0`. 
Inside the code when we listen for `suiteStarted` and `suiteDone`, we should ignore the `suite0`. Right now it gets printed out. I don't know why jasmine introduced this high level suite.
This is where it is: https://github.com/pivotal/jasmine/blob/master/src/core/Env.js#L178

And also I tried to run the tests on the code on my local machine, every test failed. Is it just me or is it happening for everyone?

**Comment by gyandeeps** [comment]
I think this is fixed now so closing this issue.

**Comment by byrhuwei** [comment]
Excuse me,how did you ignore the suit0?
