### ISSUE TITLE
PhantomJS timed out, possibly due to an unfinished async spec

### ISSUE THREAD

**Issue by vladidi** [gruntjs/grunt-contrib-jasmine#183]
I am trying to integrate 'jasmine' with 'grunt' using 'grunt-contrib-jasmine' like so:

    grunt.initConfig({
    jasmine: {
        pivotal: {
            src: ['app/js/routers/*.js', 'app/js/models/task.js', 'app/js/models/*.js', 'app/js/views/*.js'],
            options: {
                specs: 'test/spec/**/*.js',
                vendor: [
                    'app/bower_components/jquery/dist/jquery.js',
                    'app/bower_components/underscore/underscore.js',
                    'app/bower_components/backbone/backbone.js',
                    'app/bower_components/handlebars/handlebars.js',
                    'app/bower_components/bootstrap/dist/js/bootstrap.js',
                    'app/bower_components/moment/moment.js',
                    'app/bower_components/datetimepicker/jquery.datetimepicker.js',
                    'app/bower_components/backbone-tastypie/backbone_tastypie/static/js/backbone-tastypie.js',
                    'app/bower_components/bootstrap-multiselect/dist/js/bootstrap-multiselect.js',
                    'app/bower_components/bootstrap-select/dist/js/bootstrap-select.js',
                    'test/jasmine-1.2.0/jasmine.js',
                    'test/jasmine-1.2.0/jasmine-html.js',
                    'test/sinon.js'
                ]
            }
        }
    }
    });

    grunt.loadNpmTasks('grunt-contrib-jasmine');

    grunt.registerTask("test", ["jasmine"]);
And that's what I am getting :

//****TERMINAL******//

c:\some-dir>grunt test

Running "jasmine:pivotal" (jasmine) task

Testing jasmine specs via PhantomJS

Warning: PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue.

Aborted due to warnings.

c:\some-dir>

//****END OF TERMINAL******//

I really don't get it, I tried a lots of things.....

**Comment by DenEwout** [comment]
I'm having a similar issue. I provide my grunt configuration below:

```
        jasmine: {
            unittests: {
                src: 'target/js/script.js',
                options: {
                    specs: 'target/test/suiteSpec.js',
                    vendor: [
                        'target/lib/es6-promise/promise.js',
                        'target/lib/jquery/jquery.js',
                        'target/lib/jquery-ui/jquery-ui.js',
                        'target/lib/jqueryui-touch-punch/jquery.ui.touch-punch.min.js',
                        'target/lib/bootstrap/js/bootstrap.js',
                        'target/lib/bootstrap-tabdrop/bootstrap-tabdrop.js',
                        'target/lib/knockout/js/knockout.debug.js',
                        'target/lib/knockout-switch-case/knockout-switch-case.min.js',
                        'target/lib/knockstrap/knockstrap.js',
                        'target/lib/underscore/underscore.js',
                        'target/lib/backbone/backbone.js',
                        'target/lib/lodash/lodash.compat.js',
                        'target/lib/jointjs/geometry.js',
                        'target/lib/jointjs/vectorizer.js',
                        'target/lib/jointjs/joint.clean.js',
                        'target/js/ko-selectable-extender.js'
                    ]
                }
            }
        }
```

**Comment by rjmacarthy** [comment]
I am having similar issues.

**Comment by majamatic** [comment]
I am getting this issue too. After running npm install and running my tests afterwards I get this warning.
When I install the grunt-contrib-jasmine version 0.6.5 the test run well again. The warning starts with 7.0.0. Any idea?
