### ISSUE TITLE
Syntax error but Grunt said 'Done, without errors' 

### ISSUE THREAD

**Issue by noppanit** [gruntjs/grunt-contrib-jasmine#188]
I just noticed that I didn't include one library and it caused PhantomJs to complain about Syntax Error but it didn't bomb out. Do I need to set something so when errors like this happen it also fails the build?

Running "jasmine:dev" (jasmine) task
Testing jasmine specs via PhantomJS

>> Error: Syntax error, unrecognized expression: [data-'Times New Roman'-abide] at
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 fb
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 w
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> assets/vendor/foundation/js/foundation.js:102 
>> assets/vendor/foundation/js/foundation.js:685 
>> assets/vendor/foundation/js/foundation.js:349 
>> assets/vendor/foundation/js/foundation.js:315 
>> assets/vendor/foundation/js/foundation.js:620 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> assets/vendor/foundation/js/foundation.js:622 
>> assets/js/build/theme-bundle.js:754 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 
>> js-tests/vendors/jquery/jquery-1.11.1.min.js:2 J
................................................

48 specs in 0.307s.
>> 0 failures

**Comment by danielbachhuber** [comment]
@vladikoff any thoughts on how we could workaround?
