### ISSUE TITLE
please support jasmine 2.1.3

### ISSUE THREAD

**Issue by hartatovich** [gruntjs/grunt-contrib-jasmine#191]
https://github.com/jasmine/jasmine/tree/master/dist
2.1.3 stand alone

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-jasmine/blob/d21731ee8d5e7ef32102b72bcc6823214708cfe2/package.json#L35 means you'll get any newer Jasmine version. Just reinstall this task.
