### ISSUE TITLE
Junit add option for consolidate output filename

### ISSUE THREAD

**Issue by PG2000** [gruntjs/grunt-contrib-jasmine#192]
`var xmlFile = path.join(options.junit.path, 'TEST-' + testsuites.suite1.name.replace(/[^\w]/g, '') + '.xml');`

For the moment the above approach is intergrated.

Nice would be something like

options.junit.consolidatedFileName

**Comment by sindresorhus** [comment]
Can you clarify a bit. Not sure exactly what you're asking.

**Comment by PG2000** [comment]
If i configure the grunt jasmine task i have the option to consilidate the result with this option:     
    options.junit.consolidate : true|false

If i choose this option the outputted filename takes automatically the name from suite1.

I would like to see a "new" option so i have control over the junit output filename.

In the current code you can see this in line 396-399 in https://github.com/gruntjs/grunt-contrib-jasmine/blob/976b3a7fd8dfca59d64e6bf794c2f718e1626024/tasks/jasmine.js
