### ISSUE TITLE
Warning: PhantomJS failed to load your page. Use --force to continue.

### ISSUE THREAD

**Issue by vladidi** [gruntjs/grunt-contrib-jasmine#196]
Hi,

I'm running jasmine over some tests...
After some of theme, the task stop with the following warning: 
"Warning: PhantomJS failed to load your page. Use --force to continue."

I have no idea why it stop like this, but only when the task run over 0.2 ms it is happening...

Help please...

**Comment by vladidi** [comment]
Anyone?
Please its still urgent...

**Comment by marcusellis05** [comment]
+1 on this. I'm seeing the same issue and am unable to determine cause.

**Comment by marcusellis05** [comment]
https://gist.github.com/marcusellis05/eef68a940eff2dc50ec9

**Comment by marcusellis05** [comment]
It appears that the 'connect' task isn't serving up the files on port 8000. If I manually serve my files up locally on port 300 for example and point the jasmine config to that, it works fine, but of course, it would be nice to do this in a more automated way. I'll keep digging and update this issue if I find a solution.

**Comment by eltoro** [comment]
Did you try using the --debug option? I had a similar issue and found that it was a problem with the way connect was serving the files.

**Comment by marcusellis05** [comment]
So, for me this was a pretty easy fix though I think the documentation could be a bit clearer. My issue was that I had "connect" and "jasmine" tests, but I was only running the "jasmine" task. I assumed incorrectly that it would see the "connect" task config and run that automatically with the "jasmine" task or something. I fixed my problem by creating a task alias to run "connect" first followed by "jasmine":

    grunt.registerTask('test', ['connect', 'jasmine']);

**Comment by smutnyleszek** [comment]
I have the same issue. It seems that all my tests work, when I run them in small parts, but if jasmine is running for more than `0.2s`, then I get the `Warning: PhantomJS failed to load your page.` message. I tried running it with and without `grunt-contrib-connect` with same results.
