### ISSUE TITLE
PhantomJS warning results in abort 

### ISSUE THREAD

**Issue by surdu** [gruntjs/grunt-contrib-jasmine#200]
After running the jasmine task (v0.8.2), the process aborts due to a PhantomJS warning:

```
...
...
...

5 specs in 0.126s.
>> 0 failures

PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

Aborted due to warnings.
```

I don't know if this will trigger a build failure in Travis, but I'll let you know after I commit the code. From googleing aroung, I fear it will.

**Comment by surdu** [comment]
On Travis appears to work correctly. My machine OS is Ubuntu 14.04 LTS, by the way :smile:

**Comment by crobinson42** [comment]
@surdu did you find a solution to this? I'm suddenly getting the same issue:

```
PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.
```

**Comment by surdu** [comment]
No, but it was failing only on my local machine. On Travis, where I cared the most not to fail, it worked ok.
