### ISSUE TITLE
how to load vendor library after jasmine is loaded?

### ISSUE THREAD

**Issue by cesarpachon** [gruntjs/grunt-contrib-jasmine#214]
hello, trying to use jasmine-jquery (2.0.5) with grunt-contrib-jasmine (0.8.2) but jasmine-jquery init fails because the script tag  is added to the HTML before the jasmine tag (_SpecRunner.html):

    <script src="node_modules/jquery/dist/jquery.js"></script>
    <script src="node_modules/jasmine-jquery/lib/jasmine-jquery.js"></script>
    <script src=".grunt/grunt-contrib-jasmine/require.js"></script>
    <script src=".grunt/grunt-contrib-jasmine/jasmine.js"></script> 

my task:

    jasmine: {
      test:{
        src :[    '<%= watch.files %>' ],
        options: {
          version: "2.0.0",
          vendor: [
            'node_modules/jquery/dist/jquery.js',
            'node_modules/jasmine-jquery/lib/jasmine-jquery.js'
          ],
          specs : [
             'specs/helpers/*.js',
            'specs/**/*spec.js'],
          helpers : [
            'node_modules/jasmine-ajax/lib/mock-ajax.js',
            'specs/helpers/*.js'
          ],
          timeout : 10000,
          keepRunner: true,
          template: require('grunt-template-jasmine-requirejs')
        }
      }}

how can I force the jasmine-jquery library to be included after jasmine.js? or what is the suggested way to solve this?

**Comment by FlavorScape** [comment]
Same issue. can't find variable 'module' happens if angular-mocks is loaded on the page before jasmine. I looked at the generated spec file, and if I move it to after the grunt-contrib-jasmine files, it works.

**Comment by FlavorScape** [comment]
jasmine: {
            src: [
                './main/**/*.js',
                './main/templates.js',
            ],
            options: {
                keepRunner: true,
                build: true,
                vendor: [
                    'bower_components/jquery/jquery.js',
                    'bower_components/angular/angular.js',
                    'bower_components/angular-mocks/angular-mocks.js',
                    'bower_components/angular-resource/angular-resource.js',
                    'bower_components/angular-route/angular-route.js',
                    'bower_components/angular-loader/angular-loader.js',
                    'bower_components/angular-cookies/angular-cookies.js',
                   // 'bower_components/ng-table/dist/ng-table.js'

                ],
                host: 'http://127.0.0.1:8000/',
                template: require('grunt-template-jasmine-requirejs'),
                templateOptions: {
                    requireConfig: {
                        baseUrl: '.grunt/grunt-contrib-jasmine/',
                        paths: {
                            // External libraries
                            'jQUery':   'bower_components/jquery/jquery',
                            'angular': 'bower_components/angular/angular',
                            'angularCookies': 'bower_components/angular-cookies/angular-cookies',
                            'angularMocks': 'bower_components/angular-mocks/angular-mocks.js',
                            'angularResource':  'bower_components/angular-resource/angular-resource',
                            'angularRoute':  'bower_components/angular-route/angular-route'
                           // 'ngTable':  'bower_components/ng-table/dist/ng-table'

                        },
                        shim: {
                            'angular': {
                                'exports': 'angular'
                            },
                            'jQuery': {
                                'exports': '$'
                            },
                            'angular-ui.utils': {
                                deps: ['angular']
                            },
                            'angularMocks': {
                                deps: ['angular'],
                                'exports': 'angular.mock'
                            },
                            'angularResource': {
                                deps: ['angular'],
                                'exports': 'angular.resource'
                            },
                            'angularRoute': {
                                deps: ['angular'],
                                'exports': 'angular.router'
                            },
                            'angularCookies':{
                                deps: ['angular'],
                                'exports':'ngCookies'
                            },
                            'ngTable':{
                                deps: ['angular'],
                                'exports':'ngTable'
                            },

                        }
                    }
                }
            }

        },
