### ISSUE TITLE
Jasmine-core question

### ISSUE THREAD

**Issue by hackingbeauty** [gruntjs/grunt-contrib-jasmine#215]
Hello!

In my package.json for the grunt-contrib-jasmine node module, "jasmine-core" 2.3.3 is specified.  Is "jasmine-core" simply Jasmine?  I need to verify.

Also, just to confirm, if I have "jasmine-core" 2.3.3 doest that mean I'm using Jasmine 2.3.3?

Thank you for confirming.

**Comment by gyandeeps** [comment]
Based on my experience of using this module, Yes.

**Comment by hackingbeauty** [comment]
@gyandeeps Thanks!
