### ISSUE TITLE
summary: true causes a bug at jasmine.js/L.381

### ISSUE THREAD

**Issue by xGouley** [gruntjs/grunt-contrib-jasmine#217]
Activate summary: true.
Instead of having trace for my errors, I get an error from tasks/jasmine.js, line 381.
Please replace :
grunt.log.writeln(chalk.red(symbols.options.display.error) + ' ' + test.suite + ' ' + test.name);
by :
grunt.log.writeln(chalk.red(symbols[options.display].error) + ' ' + test.suite + ' ' + test.name);

to fix this :)

Thank you !

**Comment by blitboy** [comment]
This fix seems to work for me, did you create a pull request for it?

**Comment by xGouley** [comment]
Had no time these days, I will try it later...

**Comment by xGouley** [comment]
Pull request DONE today.

Thank you for a quick merge, the fix is tiny and easy to understand :)
