### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by jesseditson** [gruntjs/grunt-contrib-jasmine#222]
Hello there! I'm using this with a build process that does the following:

- uses browserify to create a `vendor.js` file
- uses browserify (and babel) to create a `test/bundle.js` file, that contains all my specs
- uses the following grunt-contrib-jasmine config:

```
jasmine: {
            src: ['dist/js/vendor.js'],
            options: {
                specs: 'dist/test/bundle.js',
                keepRunner: true,
                outfile: 'dist/test/index.html'
            }
        }
```

This works wonderfully, and is super smooth with watchify, allowing me to re-run the test suite whenever a file is changed without waiting for a re-bundle.

However, because this is bundled upstream, jasmine gives me stack traces like:

```
TypeError: 'undefined' is not an object (evaluating 'func.bind') in file:///path/to/project/test/bundle.js (line 117595) (1)
```

This is really useless, and results in lots of hunting when devs are writing tests with a TDD flow.

I'm wondering if there are roadmap plans to add sourcemap support to this library. I tried adding a global stack trace mapper, but it appears the exception is caught upstream (which makes sense), so this would need to be handled either at the jasmine level or the grunt plugin level (not sure which).

**Comment by albell** [comment]
I haven't used it but you might try:

https://github.com/novocaine/sourcemapped-stacktrace
