### ISSUE TITLE
Breaks with npm v3

### ISSUE THREAD

**Issue by zaggino** [gruntjs/grunt-contrib-jasmine#223]
npm 3.x uses flat module installing which will cause this line: https://github.com/gruntjs/grunt-contrib-jasmine/blob/1cfaa7aed72c1ca726e8b56a8799076214f3bd11/tasks/lib/jasmine.js#L68 to cause an error:
```
Running "jasmine:src" (jasmine) task
Warning: Unable to read "C:\dev\z-schema\node_modules\grunt-contrib-jasmine\node_modules\es5-shim\es5-shim.js" file (Error code: ENOENT). Use --force to continue.
```
file is now located here:
```
C:\dev\z-schema\node_modules\es5-shim\es5-shim.js
```

**Comment by jcreamer898** [comment]
I created a PR for this... https://github.com/gruntjs/grunt-contrib-jasmine/pull/225

**Comment by jcreamer898** [comment]
There's also this one too, so we'll see which makes it in... https://github.com/gruntjs/grunt-contrib-jasmine/pull/224

**Comment by starstuffharvestingstarlight** [comment]
+1 
Seeing this on npm v3.3.5 + node v0.12.7

**Comment by vladikoff** [comment]
@starstuffharvestingstarlight what version of the plugin are you suing?

**Comment by starstuffharvestingstarlight** [comment]
0.9.2

**Comment by starstuffharvestingstarlight** [comment]
@vladikoff sorry, safe to close, went through all our apps and the broken one had a wrong version setting (0.8.2) and was causing this error---updated and fixed :)

**Comment by vladikoff** [comment]
:+1:
