### ISSUE TITLE
Can't change the viewport size of PhantomJS

### ISSUE THREAD

**Issue by alexandernst** [gruntjs/grunt-contrib-jasmine#228]
https://github.com/gruntjs/grunt-contrib-jasmine/issues/128 was never answered/fixed. Is it possible to change the viewport size from `grunt-contrib-jasmine`? If "yes", how?

**Comment by Arkni** [comment]
It's not hard to do:
```js
// Example configuration
grunt.initConfig({
  jasmine: {
    pivotal: {
      src: 'src/**/*.js',
      options: {
        specs: 'spec/*Spec.js',
        helpers: 'spec/*Helper.js',

        // change the viewport size of PhantomJS
        page: {
          viewportSize: {
            width: 1280,
            height: 900
          }
        }
      }
    }
  }
});
```

**Comment by charlievaughan** [comment]
@Arkni  solution works for one viewport size but I'd like to hear if anyone know how to do this dynamically? Ideally this would be from within a Jasmine test.

Although PhantomJS has an API for resizing windows this only seems to work when part of a script run directly in PhantomJS on command line. 

So there needs to be some kind of bridge between the Jasmine script and PhantomJS. But I'm beginning to think there's no way to do this.

I'm working on a site where we are trying to retro-fit Jasmine tests to a large existing codebase without refactoring the whole thing.

**Comment by charlievaughan** [comment]
We've just come up with one workaround. 

Create a grunt-contrib-jasmine subtask for each viewport size, then run all the subtasks as part of your Grunt task like so:

`grunt.registerTask('test', ['jasmine:mobile', 'jasmine:tablet', 'jasmine:desktop']);
`
This has the downside of tripling the time it takes to run the tests.
