### ISSUE TITLE
Undefined is not an object $.ajax.calls.mostRecent().args

### ISSUE THREAD

**Issue by ritchieanesco** [gruntjs/grunt-contrib-jasmine#229]
We've recently just upgraded from 0.7.0 to 1.0.0. and all our stubbed ajax calls get this error.

This is an example of the code:

```
it('should receive a call', function () {

            spyOn($, 'ajax');
            sso.getUserDetails(api, null);
            expect($.ajax.calls.mostRecent().args[0].url).toEqual(api);

        });
```

After more investigation, if i revert back to 0.6.2 all ajax tests are working fine. We are using jQuery 1.9.1 so also wondering if it could be the jQuery version.

**Comment by steveoh** [comment]
closing as most likely upstream issue
