### ISSUE TITLE
Please publish master!!

### ISSUE THREAD

**Issue by lukeapage** [gruntjs/grunt-contrib-jasmine#231]
I have just upgraded to grunt 1.0.0

I am running into this issue:
https://github.com/gruntjs/grunt/issues/1461

It has been fixed here: https://github.com/gruntjs/grunt-contrib-jasmine/commit/0eb7cf56029b59e4abb2fc52fd5148440bbde35e

but it has not been published after 2 months.. Please can you publish master?

**Comment by vladikoff** [comment]
fixed!

**Comment by lukeapage** [comment]
Many thanks.
