### ISSUE TITLE
Fatal error: _.sprintf is not a function

### ISSUE THREAD

**Issue by alex-scown-hpe** [gruntjs/grunt-contrib-jasmine#232]
We're seeing an issue in the newly released 1.0.1 version. If phantomjs raises an error.onError event, the resulting event handler will crash when trying to print the stack trace.

    Running "jasmine:test" (jasmine) task
    Testing jasmine specs via PhantomJS

    grunt-contrib-jasmine
     - should not crash on this spec...>> Spec 'grunt-contrib-jasmine should not crash on this spec' has no expectations. at
    Fatal error: _.sprintf is not a function

The cause seems to be https://github.com/gruntjs/grunt-contrib-jasmine/blob/f1550b920402b00770a71d001f2d6d03efc2356c/tasks/jasmine.js#L206

A repo demonstrating this issue can be found at https://github.com/hpe-idol/grunt-contrib-jasmine-logging-error.

**Comment by vladikoff** [comment]
Should be fixed in 1.0.2, thanks!

**Comment by vladikoff** [comment]
There was a deprecation warning in the previous version that we were using, pushed 1.0.3 with a non deprecated package.
