### ISSUE TITLE
Unable to Test Source Setup Logic

### ISSUE THREAD

**Issue by deckar01** [gruntjs/grunt-contrib-jasmine#237]
There does not seem to be a way to spy on the vendor functions before source files are executed. To test that a source file is properly bootstrapping itself I need to be able to spy on a function in a vendor library before the source files are loaded.

There also does not seem to be a way to inject test fixtures into the DOM before vendor or source files are executed.

Am I missing something? Am I supposed to create a custom template for this pattern?

**Comment by deckar01** [comment]
Since helpers are loaded after the vendor scripts, but before the source code I was able to mock the vendor function in the helper and expose a utility for controlling the execution order of the bootstrapping logic in my tests.

```js
var __jquery_ready_list = [];

jQuery.fn.ready = function(fn) {
  __jquery_ready_list.push(fn);
}

var jqueryHelper = {};

jQueryHelper.ready = function() {
  __jquery_ready_list.forEach(function(fn) { fn(); });
  __jquery_ready_list = [];
};

afterEach(function() {
  __jquery_ready_list = [];
});
```

This should allow me to inject my HTML fixtures before the source file is executed.

**Comment by steveoh** [comment]
closing as phantomjs is not supported
