### ISSUE TITLE
specs are silently skipped when error present using phantomjs

### ISSUE THREAD

**Issue by jywarren** [gruntjs/grunt-contrib-jasmine#241]
In my setup (happy to [share more](https://github.com/publiclab/PublicLab.Editor/)), when I introduce an error to the spec code (not the code that's being tested), the whole spec is then omitted from the output silently.

See comparison here: https://gist.github.com/jywarren/d5aa67891118e5e2cd350d71d00de745

Am I perhaps doing something wrong? I'd have expected to see an error in the output. Thanks!

**Comment by tsadler1988** [comment]
+1

**Comment by samanthagmccormick** [comment]
+1 - quite horrible bug!

**Comment by steveoh** [comment]
You might need to step up to bat on this one since phantom support was dropped.

**Comment by steveoh** [comment]
closing as phantomjs is not supported
