### ISSUE TITLE
$scope.$apply() causes expectationResultFactory error.

### ISSUE THREAD

**Issue by FlavorScape** [gruntjs/grunt-contrib-jasmine#244]
Running from grunt is fine, but if I open the spec runner it generated in Chrome, I get this error:

> Uncaught TypeError: this.expectationResultFactory is not a function

This is only if I add $scope.$apply(). If I comment that out, the specs run fine in the specRunner.html. 

could be related to this, but it happens regardless of the element rendering:
http://stackoverflow.com/questions/38382684/how-come-i-cant-call-scope-apply-only-when-compiling-an-angular-element-in

**Comment by steveoh** [comment]
closing as abandoned
