### ISSUE TITLE
Tests are breaking with jasmine-core: 2.5.0

### ISSUE THREAD

**Issue by gebeuhler** [gruntjs/grunt-contrib-jasmine#246]
See:

https://github.com/jasmine/jasmine/issues/1188

We manually set jasmine-core to 2.4.1 to resolve this issue.

**Comment by vdefranc** [comment]
We did the same to fix our builds. Created a PR for this. In package.json, I set the version to ~2.4.0.

https://github.com/gruntjs/grunt-contrib-jasmine/pull/247

**Comment by nburwell** [comment]
Since https://github.com/jasmine/jasmine/issues/1188 is closed and tests are noted as fixed in 2.5.1, can this issue be closed? 

Is there any plan to bump the package.json version of jasmine-core to 2.5.x or 2.6.x?

**Comment by steveoh** [comment]
with a21b0b189b3c3df58e6350e36f3c00b5e6b03705 you can now set the version of jasmine you would like to use.
