### ISSUE TITLE
Update jasmine version

### ISSUE THREAD

**Issue by pratesim** [gruntjs/grunt-contrib-jasmine#263]
Do you have in plan to update jasmine to 2.8.0?

**Comment by srescio** [comment]
+1 [current version 2.4](https://github.com/gruntjs/grunt-contrib-jasmine/blob/master/package.json#L21) has a bug that prevents using the random flag, it was fixed in [minor 2.4.1](https://github.com/jasmine/jasmine-npm/commit/4aa555af842374ce0748a07e416e89169f669574?diff=unified)
