### ISSUE TITLE
Update lodash to latest

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-contrib-jasmine#270]
@stdavis @steveoh I tried updating to version 4 but it breaks the tests, any ideas?

**Comment by vladikoff** [comment]
I tried launching with `    const browser = await puppeteer.launch({headless: false});` to find the source of errors, but no luck so far

**Comment by stdavis** [comment]
Do the tests pass when you load `_SpecRunner.html` in non-headless (headfull? ;) Chrome? We found that loading the spec runner in regular chrome made debugging much easier.

**Comment by steveoh** [comment]
Is this a chore you would like to do for security or whatever? 

It's the lodash template function. It returns a compiled function. https://github.com/gruntjs/grunt-contrib-jasmine/pull/272 fixes this.

**Comment by steveoh** [comment]
@vladikoff thanks for the contributor privs. I'd still like you to approve/merge/deploy these changes if they are in line with the project.  happy to chat in gitter or somewhere about the new privs as well.
