### ISSUE TITLE
Display console output

### ISSUE THREAD

**Issue by arbylee** [gruntjs/grunt-contrib-jasmine#292]
There doesn't seem to be a way to get the console output since moving to puppeteer. 
It looks like previous phantomjs implementation would handle it based on the `display` flag being `full` https://github.com/gruntjs/grunt-contrib-jasmine/blob/55594d05b21665df2b58f67dded0825115b43090/tasks/jasmine.js#L196, but I don't see the puppeteer equivalent.

I think I would have expected something in https://github.com/gruntjs/grunt-contrib-jasmine/blob/master/tasks/jasmine.js to listen on the console event and pass that along.  

Something like
```
if (options.display === 'full') {
  page.on('console', (msg) => {
    grunt.log.writeln(msg.text())
  }
}
```

I can submit a PR if needed, but wanted to make sure I wasn't missing some other option for getting the console output

**Comment by steveoh** [comment]
closed by #294
