### ISSUE TITLE
npm install is broken for versions less than 2.0.0

### ISSUE THREAD

**Issue by Kevmo92** [gruntjs/grunt-contrib-jasmine#296]
Hello,

Starting today, i'm no longer able to install a version of grunt-contrib-jasmine lower than the 2.0.0 version.

For instance,
```
➜  ~ npm i grunt-contrib-jasmine@1.0.3
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for package

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kevinwatson/.npm/_logs/2019-01-07T20_57_25_326Z-debug.log
```

I can verify this on my mac (10.13.6 High Sierra) and in a docker image as well running ubuntu (16.04).

Is there a workaround for this `No valid versions available for package` ?

**Comment by Kevmo92** [comment]
I don't know what happened, but after I posted this issue I'm now able to run `npm i grunt-contrib-jasmine@1.0.3` 🤯

**Comment by pelletiermaxime** [comment]
This was because https://www.npmjs.com/package/package was deleted for an hour.
