### ISSUE TITLE
Need to pass '--allow-file-access-from-files' down to puppeteer launch args.

### ISSUE THREAD

**Issue by g2nconnell** [gruntjs/grunt-contrib-jasmine#298]
Running jasmine as part of our grunt build, headless chrome requires the argument "--allow-file-access-from-files".  This is because require tries to fetch dependencies using "file://" protocol.
Need to be able to specify this option in the grunt file and have it passed to puppeteer's launch options.

I believe this part of the reason for other user's issue of specs not running.

**Comment by steveoh** [comment]
Interesting. Up for adding a pr? We run a server and require files that way so I am not motivated to add that.

**Comment by vatsala-glory** [comment]
created the PR https://github.com/gruntjs/grunt-contrib-jasmine/pull/306
