### ISSUE TITLE
reporter.js assumes it is running headless

### ISSUE THREAD

**Issue by gordonwoodhull** [gruntjs/grunt-contrib-jasmine#303]
Similar to #25, in dc.js we rely on being able to run the generated tests in a browser using `keepRunner: true`. 

(Typically we run them headless and if there are problems, we debug in the browser.)

However, the latest PuppeteerReporter.js in 2.0.3 (Add new event-based system for sandbox communication 9371fdb90d2c) assumes that `window.sendMessage` exists. I can't seem to find this function documented, but I guess it is a headless Chrome thing.

As a workaround, I added another helper which fakes window.sendMessage:

```js
if(!window.sendMessage)
  window.sendMessage = function() {};
```

Is there a better way to continue running the tests in the browser?

**Comment by jabbany** [comment]
Sorry, this is on me. I did not realize that there is an expectation to run the pages outside of puppeteer but it makes sense one may want to do so. The fix should be a one-line change to add the noop function into the reporter.
