### ISSUE TITLE
Jasmine 3.10.0

### ISSUE THREAD

**Issue by jbest84** [gruntjs/grunt-contrib-jasmine#343]
The latest version of jasmine-core (3.10.0 and higher) contains two boot files boot0.js and boot1.js. The old boot file boot.js is now a legacyBootFile property and not exported as part of that module.

Reference:
https://github.com/jasmine/jasmine/blob/v3.10.0/lib/jasmine-core.js#L8

grunt-contrib-jasmine is using this property [here ](https://github.com/gruntjs/grunt-contrib-jasmine/blob/main/tasks/lib/jasmine.js#L81) to copy the boot file into the temp folder and assumes a single boot file.

This is breaking templates that include the boot script:

```
<% with (scripts) { %>
    <% [].concat(polyfills, jasmine, boot, vendor, helpers).forEach(function(script){ %>
    <script src="<%= script %>"></script>
    <% }) %>
  <% }; %>
```

I can work around this issue by just hard coding in the bootfiles (this will break if the config changes the folder):

```
<script src=".grunt/grunt-contrib-jasmine/boot0.js"></script>
<script src=".grunt/grunt-contrib-jasmine/boot1.js"></script>
```

**Comment by vladikoff** [comment]
This is fixed in version 4.0.0
