### ISSUE TITLE
Exit with error code on any script errors

### ISSUE THREAD

**Issue by cmc333333** [gruntjs/grunt-contrib-jasmine#64]
We're running into the same issue as described in https://github.com/jasmine-contrib/grunt-jasmine-runner/issues/20

Running `$ grunt jasmine`, we get:

```
Running "jasmine:all" (jasmine) task
Testing jasmine specs via phantom
>> TypeError: 'undefined' is not an object (evaluating '$('#sub-head')[0].offsetTop') at
[snip snip]
...............
15 specs in 0.15s.
>> 0 failures

Done, without errors.
```

The execution has the error code 0, so external tools (e.g. Travis) don't see than an error has occurred.

**Comment by Igloczek** [comment]
I don't get why it's closed without any comment, but I'm facing the same issue and looking for some solution.

**Comment by Igloczek** [comment]
@jsoverson I don't get why it's closed without any comment, but I'm facing the same issue and looking for some solution.
